### ISSUE TITLE
Missing NullCheck in ImageJ1 ij.gui.PlotWindow.java line 720

### ISSUE THREAD

**Issue by krami79** [imagej/imagej1#24]
I just stumbled across this error message when closing a live PlotWindow in ImageJ 1.51g
```
Exception in thread "Live Profiler" java.lang.NullPointerException
    at ij.gui.PlotWindow.run(PlotWindow.java:720)
    at java.lang.Thread.run(Thread.java:662)
```
I am not an ImageJ dev, but this new line should do the trick:
```java
Plot plot = plotMaker!=null?plotMaker.getPlot():null;
```

**Comment by rasband** [comment]
The latest ImageJ daily build (1.47h7) has this proposed fix.
