### ISSUE TITLE
Resetting the RoiManager from a scirpt crashes if the RoiManager was already open

### ISSUE THREAD

**Issue by avh-on1** [imagej/imagej1#46]
```
# This ImageJ python script crashes if the RoiManager is open when it is run
from ij.plugin.frame import RoiManager
roimgr = RoiManager()
roimgr.reset()
```
 As the comment says, this python script works fine if the RoiManager is not open when it is run,
but crashes if the RoiManager was already open when the script is run.

This is the resulting error:
```
Started buggy.py at Tue Oct 03 23:57:46 EDT 2017
Traceback (most recent call last):
  File "~/buggy.py", line 4, in <module>
    roimgr.reset()
	at ij.plugin.frame.RoiManager.reset(RoiManager.java:2066)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

java.lang.NullPointerException: java.lang.NullPointerException

	at org.python.core.Py.JavaError(Py.java:546)
	at org.python.core.Py.JavaError(Py.java:537)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at org.python.core.PyMethod.__call__(PyMethod.java:126)
	at org.python.pycode._pyx48.f$0(~/buggy.py:4)
	at org.python.pycode._pyx48.call_function(~/buggy.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:40)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:159)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:237)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at ij.plugin.frame.RoiManager.reset(RoiManager.java:2066)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	... 24 more
```
(file paths redacted)

**Comment by imagejan** [comment]
You can work around this by using the `RoiManager(boolean b)` constructor:

```python
from ij.plugin.frame import RoiManager
roimgr = RoiManager(True)
roimgr.reset()
```

or if you want to use the existing RoiManager instance, get it via script parameter:

```python
#@ RoiManager(required=false) roimgr
from ij.plugin.frame import RoiManager
if not roimgr:
	roimgr = RoiManager(True)
roimgr.reset()

```

**Comment by avh-on1** [comment]
The fixes suggested by @imagejan work for me.
However, the first fix - use `RoiManager(true)` - is a mystery to me.
The [documentation](https://imagej.nih.gov/ij/developer/api/ij/plugin/frame/RoiManager.html#RoiManager-boolean-) says that this constructor exists, but doesn't say how it is different from `RoiManager()`.
Can somebody explain?

**Comment by imagejan** [comment]
The `RoiManager(boolean b)` constructor doesn't contain proper javadoc, only a comment in the source code:

https://github.com/imagej/imagej1/blob/192ffb47fc4113ab032efb76a725f3fd7dcc16f0/ij/plugin/frame/RoiManager.java#L92-L98

**Comment by rasband** [comment]
I changed the JavaDoc for this constructor to

`   /** Constructs an ROIManager without displaying it. The boolean argument is ignored. */`
