### ISSUE TITLE
Delete channel locks imagej

### ISSUE THREAD

**Issue by cwood1967** [imagej/imagej1#54]
We believe we have found a bug in imagej (with Fiji):

With:

- a 3 channel time-lapse image as the active window
- The last channel as the active channel
- The Channels tool open
- Select Image->Stacks->Delete Slice is selected from the menu
- Select channel from the dropdown menu

The channels tool will close and imagej will lock up and need to be forcibly closed.

This does not occur if a channel other than the last one is active.
I was able to reproduce this on Windows and Mac with a hyper-stack created with New Hyperstack.
 
Chris

**Comment by ctrueden** [comment]
Thanks for the report, @cwood1967.

Indeed the program deadlocks. I discovered this by following [these instructions](https://imagej.net/Troubleshooting#If_ImageJ_freezes_or_hangs).

The relevant part of the thread dump is:
```
Found one Java-level deadlock:
=============================
"SciJava-306531a9-Thread-6":
  waiting to lock monitor 0x00007fa551bebc48 (object 0x0000000700c37448, a ij.CompositeImage),
  which is held by "AWT-EventQueue-0"
"AWT-EventQueue-0":
  waiting to lock monitor 0x00007fa551bebcf8 (object 0x0000000567a79e08, a java.lang.Class),
  which is held by "SciJava-306531a9-Thread-6"

Java stack information for the threads listed above:
===================================================
"SciJava-306531a9-Thread-6":
	at ij.ImagePlus.saveRoi(ImagePlus.java:1789)
	- waiting to lock <0x0000000700c37448> (a ij.CompositeImage)
	at ij.WindowManager.setCurrentWindow(WindowManager.java:43)
	at ij.WindowManager.addImageWindow(WindowManager.java:303)
	at ij.WindowManager.addWindow(WindowManager.java:285)
	- locked <0x0000000567a79e08> (a java.lang.Class for ij.WindowManager)
	at ij.WindowManager.addWindow(WindowManager.java:294)
	at ij.gui.ImageWindow.<init>(ImageWindow.java:99)
	at ij.gui.StackWindow.<init>(StackWindow.java:28)
	at ij.gui.StackWindow.<init>(StackWindow.java:24)
	at ij.ImagePlus.setStack(ImagePlus.java:703)
	at ij.ImagePlus.setStack(ImagePlus.java:733)
	at ij.plugin.StackEditor.deleteHyperstackChannelSliceOrFrame(StackEditor.java:229)
	at ij.plugin.StackEditor.deleteSlice(StackEditor.java:62)
	at ij.plugin.StackEditor.run(StackEditor.java:25)
	at ij.IJ.runPlugIn(IJ.java:198)
	at ij.IJ.runPlugIn(IJ.java:181)
	at net.imagej.legacy.command.LegacyCommand.run(LegacyCommand.java:59)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"AWT-EventQueue-0":
	at ij.WindowManager.addWindow(WindowManager.java:282)
	- waiting to lock <0x0000000567a79e08> (a java.lang.Class for ij.WindowManager)
	at ij.plugin.frame.Channels.<init>(Channels.java:31)
	at ij.plugin.frame.Channels.update(Channels.java:100)
	at ij.plugin.frame.Channels.updateChannels(Channels.java:117)
	at ij.CompositeImage.updateImage(CompositeImage.java:219)
	- locked <0x0000000700c37448> (a ij.CompositeImage)
	at ij.CompositeImage.getImage(CompositeImage.java:99)
	at ij.gui.ImageCanvas.paintDoubleBuffered(ImageCanvas.java:527)
	at ij.gui.ImageCanvas.paint(ImageCanvas.java:218)
	at ij.gui.ImageCanvas.update(ImageCanvas.java:205)
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
	at sun.lwawt.LWRepaintArea.updateComponent(LWRepaintArea.java:47)
	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
	at sun.lwawt.LWComponentPeer.handleJavaPaintEvent(LWComponentPeer.java:1314)
	at sun.lwawt.LWComponentPeer.handleEvent(LWComponentPeer.java:1198)
	at java.awt.Component.dispatchEventImpl(Component.java:4965)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Found 1 deadlock.
```

**Comment by rasband** [comment]
I am unable to reproduce this problem with either ImageJ or Fiji on OS X. This macro duplicates what I tried:

```
  run("Channels Tool...");
  newImage("HyperStack", "16-bit composite-mode label", 512, 512, 3, 1, 50);
  Stack.setChannel(3)
  run("Delete Slice", "delete=channel");
```

**Comment by ctrueden** [comment]
@rasband Your macro also does not deadlock on my machine, but the following one does:
```javascript
run("Channels Tool...");
newImage("HyperStack", "8-bit color-mode label", 400, 300, 3, 4, 5);
Stack.setChannel(3)
run("Delete Slice", "delete=channel");
```

**Comment by rasband** [comment]
The latest imageJ daily build (1.52e23) makes the ImagePlus.saveRoi() method non-synchronized, which appears to fix this bug. The source code changes are at
https://github.com/imagej/imagej1/commit/1ab7cb7a26768075d41abbc8af1750afa9276b6d
