### ISSUE TITLE
Interpreter.error(String) does not work headless

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej1#59]
When [running a macro as a headless script](https://imagej.net/Scripting_Headless) in ImageJ2, and the macro interpreter encounters an error, the `ij.macro.Interpreter.error(String)` method is called. Since ImageJ 1.51u, this method [tries to copy the error to the system clipboard](https://github.com/imagej/ImageJA/commit/b5e6255869379f6f096ea28abe27858025aef7ef#diff-00a683544f3c9c7ea2558d98cbd50509R1212), which is not allowed in headless mode:
```
java.awt.HeadlessException
	at sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:309)
	at ij.macro.Interpreter.error(Interpreter.java:1234)
	at ij.macro.Interpreter.undefined(Interpreter.java:1764)
	at ij.macro.Interpreter.lookupVariable(Interpreter.java:1707)
	at ij.macro.Interpreter.getFactor(Interpreter.java:1498)
	at ij.macro.Interpreter.getTerm(Interpreter.java:1432)
	at ij.macro.Interpreter.getExpression(Interpreter.java:1415)
	at ij.macro.Interpreter.getBooleanExpression(Interpreter.java:1061)
	at ij.macro.Interpreter.getLogicalExpression(Interpreter.java:1037)
	at ij.macro.Interpreter.getAssignmentExpression(Interpreter.java:1158)
	at ij.macro.Interpreter.doAssignment(Interpreter.java:758)
	at ij.macro.Interpreter.doStatement(Interpreter.java:267)
	at ij.macro.Interpreter.doStatements(Interpreter.java:235)
	at ij.macro.Interpreter.run(Interpreter.java:118)
	at ij.macro.Interpreter.run(Interpreter.java:89)
	at ij.macro.Interpreter.run(Interpreter.java:100)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
	at ij.IJ.runMacro(IJ.java:138)
	at ij.IJ.runMacro(IJ.java:127)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1096)
	at net.imagej.legacy.IJ1Helper$3.call(IJ1Helper.java:1092)
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1043)
	at net.imagej.legacy.IJ1Helper.runMacro(IJ1Helper.java:1092)
	at net.imagej.legacy.plugin.IJ1MacroEngine.eval(IJ1MacroEngine.java:137)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This exception can be reproduced by creating a simple macro called `hello.ijm` with only the line `hello` (not a valid ImageJ macro command). Then running:
```
$FIJI_HOME/Contents/MacOS/ImageJ-macosx --ij2 --headless --run /path/to/hello.ijm
```
With ImageJ 1.51s, the following output is given:
```
Macro Error: Undefined variable in line 2.

<hello>
```
Whereas with 1.51u and newer, the above thread dump happens.

@rasband Personally, I would favor removing this auto-copying behavior completely, since I find it impolite to overwrite the user's clipboard in that way. But if the behavior is here to stay, then I suggest wrapping the clipboard logic in a try/catch block to avoid this issue. Otherwise, whenever a macro has a problem executing in headless mode, the user will receive this same exception instead of the intended error.

**Comment by rasband** [comment]
The latest ImageJ daily build (1.52c10) avoids this issue by wrapping the clipboard logic in a try/catch block.

**Comment by ctrueden** [comment]
@rasband Thank you!
